### ISSUE TITLE
Add Oracle Database 19c to the dashboard

### ISSUE THREAD

**Issue by pbk8s** [ArmDeveloperEcosystem/ecosystem-dashboard-for-arm#237]
**Package Name**
Oracle Database 19c supports Arm64 platforms. Please add it to the list.

**(Optional): Provide the package information**
Please enter the package information for the fields as specified in [Contribution guidelines](/contrib.md).

**Comment by odidev** [comment]
Kindly find the concerned PR for Oracle SQL [here](https://github.com/ArmDeveloperEcosystem/ecosystem-dashboard-for-arm/pull/240/files).
