### ISSUE TITLE
Add Aerospike database to the ecosystem dashboard

### ISSUE THREAD

**Issue by pbk8s** [ArmDeveloperEcosystem/ecosystem-dashboard-for-arm#246]
**Package Name**
 Aerospike supports Arm64 platforms. Please add it to the dashboard.

**(Optional): Provide the package information**
(https://aerospike.com/download/)

**Comment by odidev** [comment]
Kindly refer [this](https://github.com/ArmDeveloperEcosystem/ecosystem-dashboard-for-arm/pull/280) PR for Aerospike ARM64 support.
