### ISSUE TITLE
ambiguous use of dates

### ISSUE THREAD

**Issue by dslarm** [ArmDeveloperEcosystem/ecosystem-dashboard-for-arm#252]
**Type of issue**
- [ X] Other

**Describe the issue**
The date field supplied with packages is xx/xx/yyyy.  This is ambiguous - everywhere except US: dd/mm/yyyy or in US: mm/dd/yyyy.  This repo should standardize to ISO convention of yyyy/mm/dd. It's not clear for either contributors or users.
**To Reproduce**
Change continent.
**Expected behavior**
Same date, wherever reader is.

**Comment by zachlasiuk** [comment]
Fixed this issue for all packages in the main branch, all contributions should now appear in yyyy/mm/dd. Thank you for the suggestion!
